import { IIoClass, IIo } from '../types/iquest';
export declare const printError: (msg: any, err: any, suppressTrace: any) => boolean;
export declare function msg(s: any, params: any, cssClass: any): void;
export declare function msgPre(s: any, params: any, cssClass: any): void;
export declare function msgDiv(arr: any, params: any, cssClass: any): void;
export declare function msgTable(arr: any, headings: any, params: any, cssClass: any): void;
export declare function picture(filename: any, width: any, height: any): void;
export declare function sound(filename: any): void;
export declare function ambient(filename: any, volume: any): void;
export declare function draw(width: any, height: any, data: any, options: any): void;
export declare function failedmsg(s: any, params: any): number;
export declare function falsemsg(s: any, params: any): boolean;
export declare function metamsg(s: any, params: any): void;
export declare function parsermsg(s: any): boolean;
export declare function commentmsg(s: any): boolean;
export declare function errormsg(s: any, suppressTrace: any): boolean;
export declare function debugmsg(s: any): void;
export declare function blankLine(): void;
export declare function hr(): void;
export declare function clearScreen(): void;
export declare function wait(delay: any, text: any, func: any): void;
export declare function showMenu(title: any, options: any, fn: any): void;
export declare function showMenuDiag(title: any, options: any, fn: any, cssClass: any): number;
export declare function showYesNoMenu(title: any, fn: any): void;
export declare function askText(title: any, fn: any): void;
export declare function showDiag(title: any, text: any, submitButton: any): boolean;
export declare function askDiag(title: any, fn: any, submitButton: any): number;
export declare function endTurnUI(update: any): void;
export declare function createAdditionalPane(position: any, title: any, id: any, func: any): void;
export declare const io: IIoClass;
export declare const IO: IIo;
//# sourceMappingURL=_io.d.ts.map