import { INpc } from '../types/iquest';
export declare const NPC: (isFemale: any) => any;
export declare const AGENDA_FOLLOWER: () => {};
export declare const agenda: {
    debug(s: any, npc: any, arr: any): void;
    debugS(s: any): void;
    disband(npc: any, arr: any): boolean;
    extractPath(start: any, end: any): any[];
    findPath(start: any, end: any, maxlength: any): false | any[];
    handleWaitFor(npc: any, arr: any, immediate: any): boolean | "next";
    handleWaitUntilWhile(npc: any, arr: any, reverse: any, immediate: any): boolean | "next";
    joinedBy(npc: any, arr: any): boolean;
    joining(npc: any, arr: any): boolean;
    jumpTo(npc: any, arr: any): any;
    leadTo(npc: any, arr: any): any;
    moveItem(npc: any, arr: any): any;
    moveTo(npc: any, arr: any): any;
    msg(npc: any, arr: any): boolean;
    patrol(npc: any, arr: any): boolean;
    pause(npc: any, arr: any): boolean;
    run(npc: any, arr: any): any;
    setItemAtt(npc: any, arr: any): boolean;
    showTopic(npc: any, arr: any): boolean;
    text(npc: any, arr: any): boolean;
    wait(npc: any, arr: any): boolean;
    waitFor(npc: any, arr: any): any;
    waitForNow(npc: any, arr: any): any;
    waitUntil(npc: any, arr: any): boolean | "next";
    waitUntilNow(npc: any, arr: any): boolean | "next";
    waitWhile(npc: any, arr: any): boolean | "next";
    waitWhileNow(npc: any, arr: any): boolean | "next";
    walkRandom(npc: any, arr: any): boolean;
    walkTo(npc: any, arr: any): boolean;
};
export declare const QUESTION: () => {
    sayResponse(char: any, s: any): boolean;
};
export declare const TOPIC: (fromStart: any) => {
    belongsTo(loc: any): boolean;
    conversationTopic: boolean;
    count: number;
    eventIsActive(): void;
    eventPeriod: number;
    eventScript(): void;
    hide(): boolean;
    hideAfter: boolean;
    hideTopic: boolean;
    isAtLoc: () => boolean;
    isTopicVisible(char: any): any;
    isVisible: () => boolean;
    nowHide: any[];
    nowShow: any[];
    properNoun: boolean;
    runscript(): any;
    show(): boolean;
    showHideList(list: any, isShow: any): void;
    showTopic: any;
};
export declare const ENPC: INpc;
//# sourceMappingURL=_npc.d.ts.map