import './lib/_settings';
import './lib/_util';
import './lang/lang-en';
import './lib/_file_saver';
import './lib/_saveload';
import './lib/_text';
import './lib/_io';
import './lib/_command';
import './lib/_defaults';
import './lib/_templates';
import './lib/_world';
import './lib/_npc';
import './lib/_parser';
import './lib/_commands';
//# sourceMappingURL=index.d.ts.map